### ISSUE TITLE
一定要用对应版本的jdk包么

### ISSUE THREAD

**Issue by snowjade** [flyingpiggy/thinking-In-Java#2]
可以用最新版本的jdk么，找不到 com.sun.mirror 。

**Comment by fullofinspiration** [comment]
同问

**Comment by fullofinspiration** [comment]
已经解决，在http://www.java2s.com/Code/Jar/a/Downloadaptmirrorapi01jar.htm上下载jar包后mvn install后就可以了

**Comment by xbtlin** [comment]
@fullofinspiration   很赞

**Comment by stevemelon** [comment]
@fullofinspiration niubility

**Comment by aiNiDeFang** [comment]
感谢博主！同样感谢也您@fullofinspiration
